### ISSUE TITLE
Run Error.

### ISSUE THREAD

**Issue by ZcsrenlongZ** [WU-CVGL/BAD-Gaussians#2]
![c57cd5c1fbc67a4f3da534905a1210ba png](https://github.com/WU-CVGL/BAD-Gaussians/assets/47207331/84acd017-e1ab-487f-b6cd-db76859c514d)

**Comment by LingzheZhao** [comment]
Hi, the parameter name mismatch issue is due to the recent splatfacto refactor PR in nerfstudio (https://github.com/nerfstudio-project/nerfstudio/pull/2946). I fixed it [in the newest commit](https://github.com/WU-CVGL/BAD-Gaussians/commit/185c82534327d7cc58301103c9b07126f24ae8d1) and the problem should be gone now!

**Comment by ZcsrenlongZ** [comment]
Thanks for your reply! It works! 
But I am still facing the issue and  I am not sure where is the  reason.
![c57cd5c1fbc67a4f3da534905a1210ba png png](https://github.com/WU-CVGL/BAD-Gaussians/assets/47207331/cab45bc3-e5f5-40dc-9ee0-7364b397f772)

**Comment by LingzheZhao** [comment]
It seems that the `gsplat` library is not my forked version, which you can install with:

```bash
pip install git+https://github.com/LingzheZhao/gsplat
```

after the installation the problem should be gone!

**Comment by ZcsrenlongZ** [comment]
Yes! It works! Thanks!
